### ISSUE TITLE
Question: Is it possible to version boundary sets?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#14]
What if you had, say, different version of the same boundary set that you wanted to include. How would you accomplish it with this app? For instance, let's say your state government's redistricting process created multiple drafts of next generation political boundaries. If you want to include Draft A, Draft B and the final version, how would you do it?

**Comment by onyxfish** [comment]
Currently, there is no explicit way of handling versions, though there is a ticket for it! #6  Honestly, I'm inclined to solve these sorts of issues with naming conventions rather than formal relationships, though if someone wanted to hack together a versioning system, I would be open to merging it in.

**Comment by JoeGermuska** [comment]
yeah, my reaction before seeing Chris's comment was pretty much the same; just assign 'kinds' in definitions.py

I would want to hear more use cases for versioning before voting for any specific implementation; seems too easy to do wrong if you base it just on the first case you come to.

**Comment by palewire** [comment]
Here's a couple I can think of:
- You want to compare differences and similarities between versions in an application. An example would be an application, like [this one](http://www.latimes.com/news/politics/la-redistricting-map,0,4015285.htmlstory), that shows political boundaries at different stages of a redistricting process.
- You have built one or more applications based on a particular dataset&mdash;say, Census 2000 maps&mdash;and blindly updating the API to serve a newer version of the data would make them inaccurate.

**Comment by onyxfish** [comment]
I would solve both of those problems with namespacing. Its not a perfect solution, but its dramatically less engineering overhead. In both cases your application "knows" the constraints of its requests and could be easily modified to append "_2000" or "_2010" when requesting the geographies it needs to compare. Of course, there is not reason you can't also have a non-namespaced version that serves the most current geographies.

**Comment by palewire** [comment]
Closing as stale.
