### ISSUE TITLE
Question: Is it possible to have different permissions for different boundary sets?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#15]
Let's say you wanted to have some boundaries public, and other private behind an auth wall. Could that accomplished?

**Comment by onyxfish** [comment]
As it stands the permission system is nowhere near this elaborate, but it should be straightforward to piggy-back on Django's existing auth support for something like this. This isn't something I've heard anyone else ask for, but its certainly something I'd be willing to integrate.

**Comment by palewire** [comment]
Closing as stale.
