### ISSUE TITLE
Question: How do you handle hierarchical relationships between geometry sets?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#17]
For instance, let's say you have two sets: Police divisions, and the smaller police beats that comprise them. Is there a way to make that connection within the database?

**Comment by onyxfish** [comment]
Nope, I haven't seen a compelling reason to add the complexity. Any way of using that which I can imagine can be easily facilitated by simply querying against both sets of shapes.  Do you have a use-case in mind?

**Comment by palewire** [comment]
Let's say, I want to make of a map with the shapes of every beat within a particular police division.

**Comment by onyxfish** [comment]
That's a reasonable use and currently there is nothing built into the boundaryservice that would serve this purpose. I can think of a number of ways it could be supported:
- filtering by metadata values
- pre-generating lists of which beats correspond to which police division and then adding the ability to request a comma-separated list of shapes
- actually implementing a "parent attribute" and a method of binding shapes to their parents

I'm pretty skeptical of how well-generalized the third option could be, but I'm certainly open to #1 or #2.  As a stopgap you could also load each "divisions-worth" of beats into separate BS set and then query back the whole set via naming convention.

**Comment by palewire** [comment]
Closing as stale.
