### ISSUE TITLE
Question: Is it possible in a request to limit the number of fields that will be returned?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#18]
For instance, what if I only want the name of the polygon containing a point, not its actual boundaries? Could I instruct the API to exclude the shape from the response?

**Comment by onyxfish** [comment]
You can't arbitrarily exclude any attribute, but you can decide what shape you wanted returned by passing the "shape" querystring param.

?shape=[full | simple | none]

That was one of the most requested features and one of the last I implemented as it was dependent on changes in django-tastypie.

**Comment by palewire** [comment]
Closing as stale.
