### ISSUE TITLE
configurable simplification?

### ISSUE THREAD

**Issue by jamesturk** [newsapps/django-boundaryservice#25]
Was thinking of adding the ability to tune the degree of simplification that is applied in the loadshapefiles command, probably via an optional key on the shapefile config dicts that'd default to the current value.

If this would be agreeable I'll go ahead and write it up then submit a pull request.

**Comment by onyxfish** [comment]
Absolutely, I can't think of any reason this shouldn't be configurable. I'd be happy to merge it in.

**Comment by jamesturk** [comment]
closing my own issue, pull request in #26
